spark/events/urls.py
from django.conf.urls import url
from spark.events import views

urlpatterns = [
    url(r'^$', views.events, name='events'),
    url(r'^post/$', views.post, name='post'),
    url(r'^like/$', views.like, name='like'),
    # url(r'^comment/$', views.comment, name='comment'),
    url(r'^load/$', views.load, name='load'),
    # url(r'^check/$', views.check, name='check'),
    # url(r'^update/$', views.update, name='update'),
    # url(r'^remove/$', views.remove, name='remove_feed'),
    # url(r'^(\d+)/$', views.feed, name='feed'),
]

spark/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin

from spark.activities import views as activities_views
from spark.authentication import views as spark_auth_views
from spark.core import views as core_views
from spark.search import views as search_views

urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^login', auth_views.login, {'template_name': 'core/cover.html'},
        name='login'),
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', spark_auth_views.signup, name='signup'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    url(r'^settings/upload_picture/$', core_views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture,
        name='save_uploaded_picture'),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^feeds/', include('spark.feeds.urls')),
    url(r'^questions/', include('spark.questions.urls')),
    url(r'^articles/', include('spark.articles.urls')),
    url(r'^messages/', include('spark.messenger.urls')),
    url(r'^events/', include('spark.events.urls')),
    url(r'^courses/', include('spark.courses.urls')),
    url(r'^notifications/$', activities_views.notifications,
        name='notifications'),
    url(r'^notifications/last/$', activities_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications,
        name='check_notifications'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^profile/(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

spark/events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import resolve_url as r
from spark.activities.models import Activity


class Event(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField('título', max_length=200)
    date_start = models.DateField('data')
    start = models.TimeField('início', null=True, blank=True)
    description = models.TextField('descrição', blank=True)
    address = models.TextField('local', null=True, blank=True)
    likes = models.IntegerField(default=0)

    class Meta:
        ordering = ('date_start',)
        verbose_name = 'evento'
        verbose_name_plural = 'eventos'

    def __str__(self):
        return self.title

    @staticmethod
    def get_events(from_event=None):
        if from_event is not None:
            events = Event.objects.filter(id__lte=from_event)
        else:
            events = Event.objects.all()
        return events

    @staticmethod
    def get_events_after(event):
        events = Event.objects.filter(id__gt=event)
        return events

    def calculate_likes(self):
        likes = Activity.objects.filter(activity_type=Activity.LIKE,
                                        feed=self.pk).count()
        self.likes = likes
        self.save()
        return self.likes

    def get_likes(self):
        likes = Activity.objects.filter(activity_type=Activity.LIKE,
                                        feed=self.pk)
        return likes

    def get_likers(self):
        likes = self.get_likes()
        likers = []
        for like in likes:
            likers.append(like.user)
        return likers


class Talk(models.Model):
    title = models.CharField('título', max_length=200)
    date_start = models.DateField('data')
    start = models.TimeField('início', blank=True, null=True)
    description = models.TextField('descrição', blank=True)
    speakers = models.ManyToManyField(
        'Speaker', verbose_name='palestrantes', blank=True)

    # objects = PeriodManager()

    class Meta:
        ordering = ['start']
        verbose_name = 'palestra'
        verbose_name_plural = 'palestras'

    def __str__(self):
        return self.title


class Speaker(models.Model):
    name = models.CharField('nome', max_length=255)
    slug = models.SlugField('slug')
    photo = models.URLField('foto')
    website = models.URLField('website', blank=True)
    description = models.TextField('descrição', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'palestrante'
        verbose_name_plural = 'palestrantes'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return r('speaker_detail', slug=self.slug)

spark/events/views.py
import json
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import (HttpResponse, HttpResponseBadRequest,
                         HttpResponseForbidden)
from django.shortcuts import get_object_or_404, render
from django.template.context_processors import csrf
from django.template.loader import render_to_string

from spark.decorators import ajax_required
from spark.events.models import Event

EVENTS_NUM_PAGES = 10


@login_required
def events(request):
    all_events = Event.objects.all()  # get_events()
    paginator = Paginator(all_events, EVENTS_NUM_PAGES)
    events = paginator.page(1)
    from_event = -1
    if events:
        from_event = events[0].id
    return render(request, 'events/events.html', {
        'events': events,
        'from_event': from_event,
        'page': 1,
    })


# def event(request, pk):
#     event = get_object_or_404(event, pk=pk)
#     return render(request, 'events/event.html', {'event': event})


@login_required
@ajax_required
def load(request):
    from_event = request.GET.get('from_event')
    page = request.GET.get('page')
    event_source = request.GET.get('event_source')
    all_events = Event.get_events(from_event)
    if event_source != 'all':
        all_events = all_events.filter(user__id=event_source)
    paginator = Paginator(all_events, EVENTS_NUM_PAGES)
    try:
        events = paginator.page(page)
    except PageNotAnInteger:
        return HttpResponseBadRequest()
    except EmptyPage:
        events = []
    html = ''
    csrf_token = (csrf(request)['csrf_token'])
    for event in events:
        html = '{0}{1}'.format(html,
                               render_to_string('events/partial_event.html',
                                                {
                                                    'event': event,
                                                    'user': request.user,
                                                    'csrf_token': csrf_token
                                                }))

    return HttpResponse(html)


def _html_events(last_event, user, csrf_token, event_source='all'):
    events = Event.get_events_after(last_event)
    if event_source != 'all':
        events = events.filter(user__id=event_source)
    html = ''
    for event in events:
        html = '{0}{1}'.format(html,
                               render_to_string('events/partial_event.html',
                                                {
                                                    'event': event,
                                                    'user': user,
                                                    'csrf_token': csrf_token
                                                }))

    return html


@login_required
@ajax_required
def load_new(request):
    last_event = request.GET.get('last_event')
    user = request.user
    csrf_token = (csrf(request)['csrf_token'])
    html = _html_events(last_event, user, csrf_token)
    return HttpResponse(html)


@login_required
@ajax_required
def check(request):
    last_event = request.GET.get('last_event')
    event_source = request.GET.get('event_source')
    events = Event.get_events_after(last_event)
    if event_source != 'all':
        events = events.filter(user__id=event_source)
    count = events.count()
    return HttpResponse(count)


@login_required
@ajax_required
def post(request):
    last_event = request.POST.get('last_event')
    user = request.user
    csrf_token = (csrf(request)['csrf_token'])
    event = Event()
    event.user = user
    title = request.POST['title']
    title = title.strip()
    date_start_ = request.POST['date_start']
    event.date_start = datetime.strptime(date_start_, '%d/%m/%Y')
    start_ = request.POST['start']
    event.start = datetime.strptime(start_, '%H:%M')
    event.description = request.POST['description']
    event.address = request.POST['address']
    print(request.POST['date_start'], request.POST['start'])
    if len(title) > 0:
        event.title = title[:255]
        event.save()
    html = _html_events(last_event, user, csrf_token)
    return HttpResponse(html)


@login_required
@ajax_required
def like(request):
    event_id = request.POST['event']
    event = event.objects.get(pk=event_id)
    user = request.user
    like = Activity.objects.filter(activity_type=Activity.LIKE, event=event_id,
                                   user=user)
    if like:
        user.profile.unotify_liked(event)
        like.delete()

    else:
        like = Activity(activity_type=Activity.LIKE, event=event_id, user=user)
        like.save()
        user.profile.notify_liked(event)

    return HttpResponse(event.calculate_likes())


# @login_required
# @ajax_required
# def comment(request):
#     if request.method == 'POST':
#         feed_id = request.POST['feed']
#         feed = Feed.objects.get(pk=feed_id)
#         post = request.POST['post']
#         post = post.strip()
#         if len(post) > 0:
#             post = post[:255]
#             user = request.user
#             feed.comment(user=user, post=post)
#             user.profile.notify_commented(feed)
#             user.profile.notify_also_commented(feed)
#         return render(request, 'feeds/partial_feed_comments.html',
#                       {'feed': feed})

#     else:
#         feed_id = request.GET.get('feed')
#         feed = Feed.objects.get(pk=feed_id)
#         return render(request, 'feeds/partial_feed_comments.html',
#                       {'feed': feed})


# @login_required
# @ajax_required
# def update(request):
#     first_feed = request.GET.get('first_feed')
#     last_feed = request.GET.get('last_feed')
#     feed_source = request.GET.get('feed_source')
#     feeds = Feed.get_feeds().filter(id__range=(last_feed, first_feed))
#     if feed_source != 'all':
#         feeds = feeds.filter(user__id=feed_source)
#     dump = {}
#     for feed in feeds:
#         dump[feed.pk] = {'likes': feed.likes, 'comments': feed.comments}
#     data = json.dumps(dump)
#     return HttpResponse(data, content_type='application/json')


# @login_required
# @ajax_required
# def track_comments(request):
#     feed_id = request.GET.get('feed')
#     feed = Feed.objects.get(pk=feed_id)
# return render(request, 'feeds/partial_feed_comments.html', {'feed':
# feed})


# @login_required
# @ajax_required
# def remove(request):
#     try:
#         feed_id = request.POST.get('feed')
#         feed = Feed.objects.get(pk=feed_id)
#         if feed.user == request.user:
#             likes = feed.get_likes()
#             parent = feed.parent
#             for like in likes:
#                 like.delete()
#             feed.delete()
#             if parent:
#                 parent.calculate_comments()
#             return HttpResponse()
#         else:
#             return HttpResponseForbidden()
#     except Exception:
#         return HttpResponseBadRequest()

spark/events/templates/events/events.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <link href="{% static 'css/events.css' %}?v=1" rel="stylesheet">
  <script src="{% static 'js/jquery.bullseye-1.0-min.js' %}"></script>
  <script src="{% static 'js/events.js' %}?v=1"></script>
{% endblock head %}

{% block main %}

  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <div class="page-header">
        <button type="button" class="btn btn-primary pull-right btn-compose" title="{% trans 'Press Ctrl + P to compose' %}">
          <span class="glyphicon glyphicon-share-alt"></span> Adicionar</button>
        <h1>Evento</h1>
      </div>

      <div class="panel panel-default panel-event">
        <div class="panel-heading">
          <h3 class="panel-title">Últimos eventos</h3>
        </div>
        <div class="panel-body">

          <div class="compose">
            <h2>Criar um novo evento</h2>
            <form role="form" id="compose-form">
              {% csrf_token %}
              <input type="hidden" name="last_event">
              <div class="form-group">
                <label for="id_title">Título</label>
                <input class="form-control" id="id_title" name="title"></input>
              </div>
              <div class="form-group">
                <label for="id_date_start">Data</label>
                <input class="form-control" id="id_date_start" name="date_start"></input>
              </div>
              <div class="form-group">
                <label for="id_start">Horário</label>
                <input class="form-control" id="id_start" name="start"></input>
              </div>
              <div class="form-group">
                <label for="id_description">Descrição</label>
                <textarea class="form-control" id="id_description" name="description" rows="3"></textarea>
              </div>
              <div class="form-group">
                <label for="id_address">Endereço</label>
                <input class="form-control" id="id_address" name="address"></input>
              </div>
              <div class="form-group">
                <button type="button" class="btn btn-primary btn-post">
                  <span class="glyphicon glyphicon-send"></span> Salvar
                </button>
                <button type="button" class="btn btn-default btn-cancel-compose">Cancelar</button>
              </div>
            </form>
          </div>
          <div class="stream-update">
            <a href="#"><span class="new-posts"></span> Novos eventos</a>
          </div>
          <ul class="stream">
            {% for event in events %}
              {% include 'events/partial_event.html' with event=event %}
            {% endfor %}
          </ul>
          <div class="load">
            <img src="{% static 'img/loading.gif' %}">
          </div>
          <form method="get" action="{% url 'load' %}" id="load_event" autocomplete="off">
            <input type="hidden" name="event_source" id="event_source" value="all">
            <input type="hidden" name="from_event" value="{{ from_event }}">
            <input type="hidden" name="page" value="{{ page }}">
          </form>

        </div>
      </div>
    </div>
  </div>

{% endblock main %}

spark/events/templates/events/partial_event.html
{% load i18n %}
{% load humanize %}

<li event-id="{{ event.pk }}" csrf="{{ csrf_token }}">
  <div class="event-container">
    <div class="post">
      <div>
        <h2>{{ event.date_start }}</h2>
        <span class="badge">{{ event.start }}</span><br>
        <span>{{ event.address }}</span>
      </div>
      <h2>{{ event.title }}</h2>
      <p>{{ event.description }}</p>
      <!-- <div class="interaction">
        {% if user in event.get_likers %}
          <a href="#" class="like unlike">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            <span class="text">Não gostei</span>
            (<span class="like-count">{{ event.likes }}</span>)
          </a>
        {% else %}
          <a href="#" class="like">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            <span class="text">Gostei</span>
            (<span class="like-count">{{ event.likes }}</span>)
          </a>
        {% endif %}
        <a href="#" class="comment">
          <span class="glyphicon glyphicon-comment"></span> Comentários
          (<span class="comment-count">{{ event.comments }}</span>)
        </a>
      </div> -->
      <!-- <div class="comments">
        <form role="form" method="post" action="{{ comment }}" onsubmit="return false">
          {% csrf_token %}
          <input type="hidden" name="event" value="{{ event.pk }}">
          <input type="text" class="form-control input-sm" placeholder="Escreva um comentário" name="post" maxlength="255">
        </form>
        <ol class="clearfix">
          {% comment %} Place holder to load event comments {% endcomment %}
        </ol>
      </div> -->
    </div>
  </div>
</li>